### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by enelesmai**
Added navigation bar
Added cover article
Added main article sections
Added sections
Added footer
Added media queries for small, medium and large screens
Added fixed nav when scrolling

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @enelesmai and @sergiomauz 
### You have done a really good job, continue doing the same. However, there are a few issues you need to work on before your project can be approved.
- Avoid using the keyword `!important` is your css

### Note:
- Avoid too much HTML nesting, instead employ the use of html5 new semantics like `article, section, nav, aside, footer` and others properly

### Make this change and submit for another review. I wish you all the best.
- Happy coding!
- For assistance: Contact me @rOluochKe

**Comment by enelesmai** [comment]
Change done :)

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
## Great  work, Congratulation :+1: 
You did all changes required previously. Go ahead and merge to master
_Goodluck in your next project_ *Happy coding*

**Comment by enelesmai** [comment]
Thank you @pelzolga123!

**Pull request merged**
